name: design_galileo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Utilizad este espacio para agregar las dependencias de Rive o cualquier otra que utilicéis
  rive: ^0.13.14
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.30
  path_provider: ^2.0.11
  http: ^0.13.4
  flutter_tts: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Aquí para las utilidades o assets que se agregen, animaciones, etc.
  assets:
    - assets/images/avataralumnos/
    - assets/images/galileo/
    - assets/images/icons/
  fonts:
    - family: ChalkFont
      fonts:
        - asset: assets/fonts/Schoolbell-Regular.ttf
